CONTIKI_TARGET_DIRS = . ./driver
# Master clock frequency
MCK=24000000
CFLAGS+=-DAUTOSTART_ENABLE

ifndef CONTIKI_TARGET_MAIN
CONTIKI_TARGET_MAIN = contiki-main.c
endif

CONTIKI_TARGET_DRIVER = spi-arch.c enc28j60.c ethernet-drv.c cc2500.c cc2520.c

#CONTIKI_TARGET_SOURCEFILES += $(SENSORS) $(STEPPER_ROBOT) \
# $(CODEPROP_SOURCES) $(CONTIKI_TARGET_MAIN)
CONTIKI_TARGET_SOURCEFILES += $(CONTIKI_TARGET_MAIN) $(CONTIKI_TARGET_DRIVER)

# include $(CONTIKI)/platform/$(TARGET)/apps/Makefile.apps

include $(CONTIKI)/cpu/arm/stm32f100/Makefile.stm32f100

#contiki-$(TARGET).a: ${addprefix $(OBJECTDIR)/,symbols.o}

ifndef BASE_IP
BASE_IP := 172.16.1.1
endif

### System dependent Makefile

ifndef WINDIR
  ifdef OS
    ifneq (,$(findstring Windows,$(OS)))
      WINDIR := Windows
    endif
  endif
endif
