Contiki 2.5: The Contiki/uIP interface
The Contiki/uIP interface
The uIP TCP/IP stack
TCP/IP support in Contiki is implemented using the uIP TCP/IP stack.
Files
file tcpip.h
Header for the Contiki/uIP interface.
Defines
#define UIP_APPCALL tcpip_uipcall
The name of the application function that uIP should call in response to TCP/IP events.
Variables
CCIF process_event_t tcpip_event
The uIP event.
TCP functions
CCIF void tcp_attach (struct uip_conn *conn, void *appstate)
Attach a TCP connection to the current process.
CCIF void tcp_listen (u16_t port)
Open a TCP port.
CCIF void tcp_unlisten (u16_t port)
Close a listening TCP port.
CCIF struct uip_conn * tcp_connect (uip_ipaddr_t *ripaddr, u16_t port, void *appstate)
Open a TCP connection to the specified IP address and port.
void tcpip_poll_tcp (struct uip_conn *conn)
Cause a specified TCP connection to be polled.
#define tcp_markconn(conn, appstate) tcp_attach(conn, appstate)
UDP functions
void udp_attach (struct uip_udp_conn *conn, void *appstate)
Attach the current process to a UDP connection.
CCIF struct uip_udp_conn * udp_new (const uip_ipaddr_t *ripaddr, u16_t port, void *appstate)
Create a new UDP connection.
struct uip_udp_conn * udp_broadcast_new (u16_t port, void *appstate)
Create a new UDP broadcast connection.
CCIF void tcpip_poll_udp (struct uip_udp_conn *conn)
Cause a specified UDP connection to be polled.
#define udp_markconn(conn, appstate) udp_attach(conn, appstate)
#define udp_bind(conn, port) uip_udp_bind(conn, port)
Bind a UDP connection to a local port.
TCP/IP packet processing
unsigned char tcpip_do_forwarding
This function does address resolution and then calls tcpip_output.
unsigned char tcpip_is_forwarding
CCIF void tcpip_input (void)
Deliver an incoming packet to the TCP/IP stack.
u8_t tcpip_output (void)
Output packet to layer 2 The eventual parameter is the MAC address of the destination.
void tcpip_set_outputfunc (u8_t(*f)(void))
#define tcpip_set_forwarding(forwarding) tcpip_do_forwarding = (forwarding)
Detailed Description
TCP/IP support in Contiki is implemented using the uIP TCP/IP stack.
For sending and receiving data, Contiki uses the functions provided by the uIP module, but Contiki adds a set of functions for connection management. The connection management functions make sure that the uIP TCP/IP connections are connected to the correct process.
Contiki also includes an optional protosocket library that provides an API similar to the BSD socket API.
See also:
The uIP TCP/IP stack
Protosockets library
Define Documentation
#define udp_bind (conn, port) uip_udp_bind(conn, port)
Bind a UDP connection to a local port.
This function binds a UDP connection to a specified local port.
When a connection is created with udp_new(), it gets a local port number assigned automatically. If the application needs to bind the connection to a specified local port, this function should be used.
Note:
The port number must be provided in network byte order so a conversion with UIP_HTONS() usually is necessary.
Parameters:
conn A pointer to the UDP connection that is to be bound.
port The port number in network byte order to which to bind the connection.
Definition at line 262 of file tcpip.h.
Referenced by simple_udp_register(), and udp_broadcast_new().
Function Documentation
CCIF void tcp_attach (struct uip_conn * conn, void * appstate)
Attach a TCP connection to the current process.
This function attaches the current process to a TCP connection. Each TCP connection must be attached to a process in order for the process to be able to receive and send data. Additionally, this function can add a pointer with connection state to the connection.
Parameters:
conn A pointer to the TCP connection.
appstate An opaque pointer that will be passed to the process whenever an event occurs on the connection.
CCIF struct uip_conn* tcp_connect (uip_ipaddr_t * ripaddr, u16_t port, void * appstate) [read]
Open a TCP connection to the specified IP address and port.
This function opens a TCP connection to the specified port at the host specified with an IP address. Additionally, an opaque pointer can be attached to the connection. This pointer will be sent together with uIP events to the process.
Note:
The port number must be provided in network byte order so a conversion with UIP_HTONS() usually is necessary.
This function will only create the connection. The connection is not opened directly. uIP will try to open the connection the next time the uIP stack is scheduled by Contiki.
Parameters:
ripaddr Pointer to the IP address of the remote host.
port Port number in network byte order.
appstate Pointer to application defined data.
Returns:
A pointer to the newly created connection, or NULL if memory could not be allocated for the connection.
CCIF void tcp_listen (u16_t port)
Open a TCP port.
This function opens a TCP port for listening. When a TCP connection request occurs for the port, the process will be sent a tcpip_event with the new connection request.
Note:
Port numbers must always be given in network byte order. The functions UIP_HTONS() and uip_htons() can be used to convert port numbers from host byte order to network byte order.
Parameters:
port The port number in network byte order.
Examples:
example-psock-server.c.
CCIF void tcp_unlisten (u16_t port)
Close a listening TCP port.
This function closes a listening TCP port.
Note:
Port numbers must always be given in network byte order. The functions UIP_HTONS() and uip_htons() can be used to convert port numbers from host byte order to network byte order.
Parameters:
port The port number in network byte order.
CCIF void tcpip_input (void)
Deliver an incoming packet to the TCP/IP stack.
This function is called by network device drivers to deliver an incoming packet to the TCP/IP stack. The incoming packet must be present in the uip_buf buffer, and the length of the packet must be in the global uip_len variable.
Definition at line 540 of file tcpip.c.
References NULL, process_post_synch(), uip_ext_len, and uip_len.
Referenced by mac_ethernetToLowpan().
void tcpip_poll_tcp (struct uip_conn * conn)
Cause a specified TCP connection to be polled.
This function causes uIP to poll the specified TCP connection. The function is used when the application has data that is to be sent immediately and do not wish to wait for the periodic uIP polling mechanism.
Parameters:
conn A pointer to the TCP connection that should be polled.
CCIF void tcpip_poll_udp (struct uip_udp_conn * conn)
Cause a specified UDP connection to be polled.
This function causes uIP to poll the specified UDP connection. The function is used when the application has data that is to be sent immediately and do not wish to wait for the periodic uIP polling mechanism.
Parameters:
conn A pointer to the UDP connection that should be polled.
Definition at line 690 of file tcpip.c.
References process_post().
Referenced by resolv_query().
void udp_attach (struct uip_udp_conn * conn, void * appstate)
Attach the current process to a UDP connection.
This function attaches the current process to a UDP connection. Each UDP connection must have a process attached to it in order for the process to be able to receive and send data over the connection. Additionally, this function can add a pointer with connection state to the connection.
Parameters:
conn A pointer to the UDP connection.
appstate An opaque pointer that will be passed to the process whenever an event occurs on the connection.
Definition at line 309 of file tcpip.c.
References uip_udp_conn::appstate, and PROCESS_CURRENT.
struct uip_udp_conn* udp_broadcast_new (u16_t port, void * appstate) [read]
Create a new UDP broadcast connection.
This function creates a new (link-local) broadcast UDP connection to a specified port.
Parameters:
port Port number in network byte order.
appstate Pointer to application defined data.
Returns:
A pointer to the newly created connection, or NULL if memory could not be allocated for the connection.
Definition at line 338 of file tcpip.c.
References NULL, udp_bind, udp_new(), and uip_ipaddr.
CCIF struct uip_udp_conn* udp_new (const uip_ipaddr_t * ripaddr, u16_t port, void * appstate) [read]
Create a new UDP connection.
This function creates a new UDP connection with the specified remote endpoint.
Note:
The port number must be provided in network byte order so a conversion with UIP_HTONS() usually is necessary.
See also:
udp_bind()
Parameters:
ripaddr Pointer to the IP address of the remote host.
port Port number in network byte order.
appstate Pointer to application defined data.
Returns:
A pointer to the newly created connection, or NULL if memory could not be allocated for the connection.
Definition at line 320 of file tcpip.c.
References uip_udp_conn::appstate, NULL, PROCESS_CURRENT, and uip_udp_new().
Referenced by simple_udp_register(), and udp_broadcast_new().
Variable Documentation
unsigned char tcpip_do_forwarding
This function does address resolution and then calls tcpip_output.
Is forwarding generally enabled?
CCIF process_event_t tcpip_event
The uIP event.
This event is posted to a process whenever a uIP event has occurred.
Definition at line 84 of file tcpip.c.