Contiki 2.5: Beeper interface
Beeper interface
The ESB Embedded Sensor Board
Files
file beep.h
Interface to the beeper.
file beep.h
Interface to the beeper.
file beep.h
Interface to the beeper.
Functions
void beep_beep (int len)
Beep for a specified time.
void beep_alarm (int alarmmode, int len)
Beep an alarm for a specified time.
void beep (void)
Produces a quick click-like beep.
void beep_down (int len)
A beep with a pitch-bend down.
void beep_on (void)
Turn the beeper on.
void beep_off (void)
Turn the beeper off.
void beep_spinup (void)
Produce a sound similar to a hard-drive spinup.
void beep_long (clock_time_t len)
Beep for a long time (seconds)
Function Documentation
void beep (void)
Produces a quick click-like beep.
This function produces a short beep that sounds like a click.
Produces a quick click-like beep.
This routine simply toggles a port pin at an audio frequency, which causes a tone to be emitted from the Raven's speaker. The beep consists of two tones at two different frequencies. At the end, the beeper port pin is kept low, which causes the speaker amplifier to shut down.
This function produces a short beep that sounds like a click.
Produces a quick click-like beep.
Produces a quick click-like beep.
This routine simply toggles a port pin at an audio frequency, which causes a tone to be emitted from the Raven's speaker. The beep consists of two tones at two different frequencies. At the end, the beeper port pin is kept low, which causes the speaker amplifier to shut down.
This function produces a short beep that sounds like a click.
Definition at line 62 of file beep.c.
References beep_beep(), and BEEP_PORT.
Referenced by uart_serial_rcv_frame().
void beep_alarm (int alarmmode, int len)
Beep an alarm for a specified time.
This function causes the beeper to beep for the specified time. The time is measured in the same units as for the clock_delay() function.
Note:
This function will hang the CPU during the beep.
This function will stop any beep that was on previously when this function ends.
If the beeper is turned off with beep_off() this call will still take the same time, though it will be silent.
Parameters:
alarmmode The alarm mode (BEEP_ALARM1,BEEP_ALARM2)
len The length of the beep.
Definition at line 42 of file beep.c.
References clock_delay().
void beep_beep (int len)
Beep for a specified time.
This function causes the beeper to beep for the specified time. The time is measured in the same units as for the clock_delay() function.
Note:
This function will hang the CPU during the beep.
This function will stop any beep that was on previously when this function ends.
If the beeper is turned off with beep_off() this call will still take the same time, though it will be silent.
Parameters:
len The length of the beep.
Definition at line 48 of file beep.c.
References clock_delay().
Referenced by beep(), beep_down(), and beep_spinup().
void beep_down (int len)
A beep with a pitch-bend down.
This function produces a pitch-bend sound with deecreasing frequency.
Parameters:
len The length of the pitch-bend.
Definition at line 60 of file beep.c.
References beep_beep(), and clock_delay().
void beep_long (clock_time_t len)
Beep for a long time (seconds)
This function produces a beep with the specified length and will not return until the beep is complete. The length of the beep is specified using CLOCK_SECOND: a two second beep is CLOCK_SECOND * 2, and a quarter second beep is CLOCK_SECOND / 4.
Note:
If the beeper is turned off with beep_off() this call will still take the same time, though it will be silent.
Parameters:
len The length of the beep, measured in units of CLOCK_SECOND
Definition at line 89 of file beep.c.
References clock_wait().
void beep_off (void)
Turn the beeper off.
This function turns the beeper off after it has been turned on with beep_on().
Definition at line 72 of file beep.c.
void beep_on (void)
Turn the beeper on.
This function turns on the beeper. The beeper is turned off with the beep_off() function.
Definition at line 66 of file beep.c.
void beep_spinup (void)
Produce a sound similar to a hard-drive spinup.
This function produces a sound that is intended to be similar to the sound a hard-drive makes when it starts.
Definition at line 78 of file beep.c.
References beep_beep(), and clock_delay().
Referenced by main().